title: Maschinendeck

name: Maschinendeck
url: http://www.maschinendeck.org
description: Hacker, Maker & Nerd Space in Trier, Germany

permalink: /:year/:month/:day/:title/
# paginate: 10
# highlighter: pygments

baseurl: "" # the subpath of your site, e.g. /blog
email: info@maschinendeck.org
twitter_username: Maschinendeck_
github_username:  maschinendeck

port: 4010

# Build settings
markdown: kramdown
